### ISSUE TITLE
Check_ind_exists("ind_1") provides False in code example

### ISSUE THREAD

**Issue by Forerunner2012** [EmaroLab/armor_py_api#1]
Dear EmaroLab,
I am currently investigating the possibilities to use ontologies with ROS as simple as possible in C++, Pyhton or Java. Your framework has catch my attention by it ability to be easy and perhaps safe to use. 

However, I have an issue trying to get individuals from your example in [client_test.py](https://github.com/EmaroLab/armor_py_api/blob/master/scripts/armor_api/client_test.py) or the pizza from the [Java AMOR](https://github.com/EmaroLab/multi_ontology_reference).
The function `client.query.check_ind_exists("ind_1")` doesn't return the expected result that is `True `in [client_test.py](https://github.com/EmaroLab/armor_py_api/blob/master/scripts/armor_api/client_test.py). I have attached the logs from the ARMORMainService terminal.
In the same way, loading pizza.owl and listing existing individuals using the function or sparql query doesn't work for me.

Could you possibly guide me on these concerns ?
I have tried also to test it on the java version of the [ARMOR client](https://github.com/EmaroLab/multi_ontology_reference) more extended, but I have difficulties to run the examples and correctly import the library in a new created package.
[ARMORlogs.txt](https://github.com/EmaroLab/armor_py_api/files/1667651/ARMORlogs.txt)

**Comment by alessio-cpt** [comment]
Hello,

I'm glad you are using our software. I hope I'll be able to help you.

First of all I would suggest you to run `client_test.py`. In this test we use the same function as you do. If you get as output `Success! ind_1 is in Class_4 now!`, that means `check_ind_exist` is working.

I tried this on a VM and it works for me. I even fixed a bug that could have prevented you from launching the test. So, update the repo and try yourself.

If the test is working, then something is wrong with your application. The most common cause for this kind of problems is that the uri you initialize the ontology reference with is wrong and does not match the one in the file. In this case, even if you look for the right individual, the request will fail because the system will look for the individual under the wrong uri.

To check the uri, open the owl file with a text editor and look for the uri. If they do not match, modify one of them so they do.

Sometimes, opening a reference, saving it, closing it and then reopening it, also appears to solve the problem.

If all of this fails, @buoncubi has more experience with this issue and can help you more.

Also, pay attention that [this](https://github.com/EmaroLab/multi_ontology_reference) is not a Java version of ARMOR. This is the Java library ARMOR is built upon. It is not a ros node and cannot be ros-launched, even though there are a few executable examples included. If you want to include it in a new package, you can take as an example ARMOR, and in particular the `build.gradle` file inside `armor_interface_service` folder. 

I would still suggest you to stick to ARMOR unless you really need the extra features.

Please let us know if you need more help!

**Comment by Forerunner2012** [comment]
Hello @alessio-cpt and @buoncubi  ,
Many thanks for the prompt reply. I have sticked to the base example in the `armor_py_api` with some tries on the pizza ontology (using it as storage more than inference). Its in these tests, that I had difficulties to get the individuals (from 'Thing' or 'Country') so turn back to the `armor_py_api` examples.

I currently can run the client `client_test.py` with the expected outputs.
`Added ind_1 to Class_1
Added ind_2 to Class_2
Added ind_3 to Class_3
Success! ind_1 is in Class_4 now!`

Since I get the output `Success! ind_1 is in Class_4 now!`, that means the boolean of `len(client.query.ind_b2_class("Class_4")) == 1` returns `True`. Thus the `client.query.ind_b2_class("Class_4")` works fine and acknowledges that the inference have been done by the reasoner.

However, the problem remains on the `check_ind_exist`. Since it is not used as value in the `client_test.py`, I printed it (line 50 `client.query.check_ind_exists("ind_1"))`. It reveals that the assertion is false (thats `ind_1` doesn't exist) which is wrong since the next function acknowledges it existence. 

So I investigate a bit on the functions calls and found out that the function `check_ind_exists` is based on `ind_b2_class("Thing")` which returns an empty list whereas 3 individuals shall exist.
In brief, the follwing calls 
`print client.query.check_ind_exists("ind_1") 
print client.query.ind_b2_class("Thing")`
provides those outputs but they are not the ones expected, right ?
`False
[]
`
Is it a behavior that only me have ?

In the future work with your software, I will for sure take care about using the uri and reference in service calls. The _rosjava_ package and subprojects brought some misunderstanding. I will try first to understand and master the AMOR service functions first and then will use extra features. I will try to have a scenario on pizza running in Python to assess the correctness of the outputs.

Thank you in advance,

**Comment by alessio-cpt** [comment]
I checked and you were right. This was a known bug of ARMOR, that was fixed by implementing a new directive (`QUERY_IND_`),  As we do not use `armor_py_api` very often, it was not updated accordingly. I pushed a fix for it. Let us know if the problem persists for you. Closing.
